#!/usr/bin/env python
from __future__ import division
import os, sys
import matplotlib.pyplot as plt
import numpy as np
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../.."))
from finance import taxes

filing_status = "single"
income = np.logspace(3.5, 6.5, 500)
fig, ax = plt.subplots()
for year in [2017, 2018]:
    tax = taxes.TaxFiler(year, filing_status).income_tax
    ax.plot(income,
            np.vectorize(lambda x: 100 * tax(x) / x)(income),
            label="{} {}".format(year, filing_status))
ax.set_xscale("log")
ax.set_xlabel("taxable income [USD]")
ax.set_ylabel("effective federal income tax rate [%]")
ax.legend()
plt.show()
