#!/usr/bin/env python
import argparse, sys
import colorspacious
import matplotlib.colors
import numpy
import scipy.misc
import colorspace # local module

def hsv_equalize(src_fn, dst_fn, max_C, min_J, max_J, gamma):
    img = scipy.misc.imread(src_fn)
    if img.shape[2] == 4:
        alpha = img[..., 3]
        img = img[..., :3]
    else:
        alpha = None
    img = colorspace.rgb_to_hls(img / 255.0)

    h = img[..., 0]                     # hue
    J = img[..., 1]                     # brightness
    C = img[..., 2]                     # chroma

    J = min_J + (max_J - min_J) * J ** gamma
    img = numpy.stack([
        360.0 * h,
        J,
        # force chroma to go through zero when brightness is at 0
        max_C * C * numpy.clip(numpy.sin(J * numpy.pi / 100.0), 0.0, 1.0),
    ], axis=-1)

    img = colorspacious.cspace_convert(img, "hJC", "sRGB255")
    if alpha is not None:
        img = numpy.concatenate([img, alpha[..., numpy.newaxis]], axis=-1)
    scipy.misc.toimage(img, cmin=0.0, cmax=255.0).save(dst_fn)

p = argparse.ArgumentParser(
    description="Make an HSV image more perceptually uniform")
p.add_argument("src_fn", metavar="source_image")
p.add_argument("dst_fn", metavar="dest_image")
p.add_argument("--max-C", type=float, default=20.0,
               help=("maximum chroma of the result is (default: 20.0). "
                     "Typical range: 0.0 to 100.0."))
p.add_argument("--min-J", type=float, default=0.0,
               help=("minimum brightness (default: 0.0). "
                     "Range: 0.0 to 100.0."))
p.add_argument("--max-J", type=float, default=100.0,
               help=("maximum brightness (default: 100.0). "
                     "Range: 0.0 to 100.0."))
p.add_argument("--gamma", type=float, default=1.0,
               help=("additional gamma correction (default: 1.0). "
                     "Range: 0.0 to infinity"))
hsv_equalize(**vars(p.parse_args()))
