#!/bin/sh
set -e

DOCDIR=???
REMOTE=git@github.com:???
doc_cmd() { ???; }

[ -d "$DOCDIR/.git" ] || (

    mkdir -p "$DOCDIR"
    cd "$DOCDIR"
    git init
    git config user.name Bot
    git config user.email "<>"
    git commit -m _ --allow-empty
    git remote add origin "$REMOTE"

)

doc_cmd
cd "$DOCDIR"
git add -A
git commit --amend -q -m Autogenerated
git push -f origin master:gh-pages
